### ISSUE TITLE
spectorJS captured framebuffer with balck&white background and gray&white background

### ISSUE THREAD

**Issue by yujiezhang125** [BabylonJS/Spector.js#192]

**Comment by yujiezhang125** [comment]
Hi there,



When observing spectorJS cpateres I found there is a little difference between frambuffers.
As the pictures below,
![WeChat Image_20210401163314](https://user-images.githubusercontent.com/56212236/113267676-34843380-9309-11eb-88e5-21ffb6cbe5da.png)
![WeChat Image_20210401163327](https://user-images.githubusercontent.com/56212236/113267695-38b05100-9309-11eb-9335-5cf0a73c3f13.png)


In different WebGL programs and under different framebuffer statements, the captured frame shows different background color.
Sometimes it's black&white grided and sometimes it's grey&white grided.

I'm wondering what's the different background color means in spectorJS logic.
It that related to the framebuffer's attachments or color/texture/stensil state?



Thanks a lot in advance for your help!

**Comment by JannikGM** [comment]
I don't think it's a "feature" in spector.js.

I assume you have a 50% white background in your image (something like `gl.clearColor(0.5, 0.5, 0.5, 0.5); gl.clear(gl.COLOR_BUFFER_BIT);`). However, it's hard to tell without having access to your website.

It would be easier to debug if we had #183 / #184 (for surfaces).

**Comment by yujiezhang125** [comment]
OK Got you!

Thank you for the advice, I'll go through my code in detail and check up.
Since the webgl program is based on a more complicated framework, and I'm not sure how to share the website.
If it's possible, I saved the json files which could be loaded in spectorJS and in which you can see most relevant shader program information.

Please find two json files here inside the zip file.
Thanks a lot!

[differentGridJSONFile.zip](https://github.com/BabylonJS/Spector.js/files/6243284/differentGridJSONFile.zip)

**Comment by JannikGM** [comment]
It's like I said; sometimes you clear with 0,0,0,1 and sometimes with 0.8,0.8,0.8,0.8.

I suggest watching #183 / #184 as this would have avoided the confusion.
We should also display vec4 / RGBA values as colored shape in the UI to make it easier to spot strange parameters.

You might also be leaking framebuffers, because one of the traces has framebuffer ID 246.
You also seem to bind without clearing, so there seems to be the expectation that the framebuffer was previously cleared. This is potentially bad for performance or even compatibility.

**Comment by sebavan** [comment]
Both samples are using a pretty different FBO setup texture vs renderBuffer and you not cleared the same way.

**Comment by yujiezhang125** [comment]
Thank you very much for your helpful reply!
