### ISSUE TITLE
ThreeJS WebGLMultisampleRenderTarget not captured

### ISSUE THREAD

**Issue by tomorrowevening** [BabylonJS/Spector.js#205]
"No frames detected. Try moving the camera or implementing requestAnimationFrame" reported when capturing [this page](https://threejs.org/examples/webgl2_multiple_rendertargets.html)

**Comment by sebavan** [comment]
This is because the sample does not use RAF or timeout but rather renders on demand when moving or resizing the window you can capture with the capture button for a certain amount of commands:

![image](https://user-images.githubusercontent.com/16655165/131326775-6efa6aca-7a7e-42d7-b64a-035aa8fbcdcc.png)

and get your result:

![image](https://user-images.githubusercontent.com/16655165/131326869-2252a788-d5ef-43ab-bfe5-4fc633703ad1.png)

**Comment by tomorrowevening** [comment]
🙌 Thank you!
