### ISSUE TITLE
Can this tool support printing depthStencilTexture which dataType is DEPTH24_STENCIL8

### ISSUE THREAD

**Issue by HannesAnWang** [BabylonJS/Spector.js#210]
We need a technical support for  printing DepthStencilTexture which dataType is DEPTH24_STENCIL8.
Now this tool can only print RGBA UNSIGNED_BYTE texture(color Texture) as uniform sampler2D source.
Can this tool support printing depthStencilTexture which dataType is DEPTH24_STENCIL8 ?

**Comment by JannikGM** [comment]
What do you mean by "printing"?

Displaying a 24 bit depth-buffer in 8-bit per channel RGB is often not very practical, unless it is displayed as linearized grayscale image, or using some rainbow pattern, but then it also doesn't represent actual buffer contents.

8-bit stencil content is also hard to display, because different algorithms use it so differently. One would need to support multiple palettes.

In general, it would be nice if it was possible to extract buffers and surfaces to raw files or high-precision images (EXR or TIFF probably). This could be seen as an extension of #184.

**Comment by sebavan** [comment]
I have added it in #184 for tracking purpose so I can close the dup.

@HannesAnWang, as @JannikGM mentioned it is definitely smthg simple as it needs quite some conversions to be visually usable.
