### ISSUE TITLE
Inspecting Immutable Textures

### ISSUE THREAD

**Issue by Descryant** [BabylonJS/Spector.js#227]
Hey! First of all, thanks for putting together this tool; it's been extremely helpful so far! However, it appears that immutable textures can't be viewed in the draw call inspector.

MWE: https://github.com/Descryant/immutable-texture-spector-mwe

The lines in question are part of [main.js](https://github.com/Descryant/immutable-texture-spector-mwe/blob/main/main.js#L65). When uploading the image data with `texImage2D` (mutable storage), everything works fine:

![image](https://user-images.githubusercontent.com/50448151/154493908-64f18ae5-967f-4ac9-915c-204b3340c630.png)

Now for the problem: If the texture storage is immutable (`texStorage2D` + `texSubImage2D`) with the exact same parameters, the render output remains the same but the properties `textureType`, `format`, `internalformat`, `width` and `height` are missing and no image shows up in the inspector:

![image](https://user-images.githubusercontent.com/50448151/154494043-f0540c92-c463-4038-a1ee-f958d0173144.png)

To reproduce, comment out line 65 and uncomment lines 68 and 69.

Is this a usage error on my part or a bug / missing feature?

Cheers!

**Comment by JannikGM** [comment]
I quickly skimmed over the related Spector.js code and this looks like your use-case should be supported:

https://github.com/BabylonJS/Spector.js/blob/b97bc8560aeb3893f8f90e084955638ae2b5c54d/src/backend/recorders/texture2DRecorder.ts#L121

I assume that hook isn't called or it's called incorrectly / rejects your call.
I don't have time to debug this further though, but given your MWE, you can probably figure it out.

It looks like the texture is then being read here:

https://github.com/BabylonJS/Spector.js/blob/1121b4c9ea0a86b58facf83e3707582202042936/src/backend/states/drawCalls/drawCallTextureInputState.ts#L75

So it's probably not displayed due to missing information. However, there shouldn't be any need to have explicit support for the `texSubImage2D` call in Spector.js, due to fallbacks in `isSupportedCombination` and the data being retrieved from the texture, instead of capturing it from texture uploads).

**Comment by Descryant** [comment]
Thanks for the pointers. I'll update this thread when I get around to looking at the problem again. This wasn't a terribly high priority for me so it may be a little while. Cheers!
