### ISSUE TITLE
glReadPixels: format and type incompatible with the current read framebuffer

### ISSUE THREAD

**Issue by quanterion** [BabylonJS/Spector.js#39]
I try to use Spector with WebGL2 MRT render. I have two framebuffers with 3 R8G8B8A8 attachements
When I started capture I will get errors 
[.Offscreen-For-WebGL-0A503658]GL ERROR :GL_INVALID_OPERATION : glReadPixels: format and type incompatible with the current read framebuffer.
Is WebGL2 MRT supported?

**Comment by sebavan** [comment]
It should be, could you please share a test url or project so that I can troubleshoot tomorrow ?

**Comment by sebavan** [comment]
@quanterion I tried to repro but unfortunately it works on this use case: https://www.babylonjs.com/demos/ssao2/

![image](https://user-images.githubusercontent.com/16655165/26840913-ad59b0aa-4a9c-11e7-8ff4-4689b019c0cb.png)

I would definitely need some pointers to your use case in order to reproduce the issue.

Thank you,

**Comment by sebavan** [comment]
@quanterion any news or can I close the issue ?

**Comment by quanterion** [comment]
Yeah, thank you, I close it for now because everything works ok in Google Chrome. I have some problems with Opera browser in debug build, try to investigate it later

**Comment by sebavan** [comment]
Interesting, please let me know what you find.
